### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/mobile-toolkit#113]
![angular 2 cli ng new app --mobile](https://cloud.githubusercontent.com/assets/18028768/20246386/d60ae296-a9f0-11e6-8aef-4f7aca94a065.png)

![angular 2 cli ng new app --mobile error](https://cloud.githubusercontent.com/assets/18028768/20246385/d608a0da-a9f0-11e6-8ffb-9f51097108f3.png)

https://www.youtube.com/watch?v=vAb-2d1vcg8&index=1&list=PL1w1q3fL4pmjq12-sSbQt5BTuHmCVKaqh
https://mobile.angular.io/

**Comment by webmaxru** [comment]
Have a look at Issue #108

**Comment by born2net** [comment]
I also open a bug hopefully we can support AOT mode and so we won't even need the ng module universal
