### ISSUE TITLE
Any guidance on how to use this without the --mobile (without cli)?

### ISSUE THREAD

**Issue by worldspawn** [angular/mobile-toolkit#115]
Is it possible to use this without the cli? Is there any guidance available on how to do this?

**Comment by gdi2290** [comment]
you can check out and download @angular/service-worker
https://github.com/angular/mobile-toolkit/tree/master/service-worker

**Comment by webmaxru** [comment]
Probably the only repo using @angular/app-shell and @angular/service-worker at the moment is my demo for the Mobile Toolkit workshop at ngPoland (all is Gulp based, no need for CLI):
https://github.com/webmaxru/pwa-guide-ngpoland/tree/step-dashboard

**Comment by worldspawn** [comment]
Thank you gentlemen
