### ISSUE TITLE
Update rxjs

### ISSUE THREAD

**Issue by gatimus** [angular/mobile-toolkit#117]
```
Error: Cannot find module 'rxjs/add/operator/cache'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at path\to\project\node_modules\@angular\service-worker\bundles\service-worker.umd.js:2:466
    at Object.<anonymous> (path\to\project\node_modules\@angular\service-worker\bundles\service-worker.umd.js:5:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
When importing '@angular/service-worker'.

**Comment by cyrilletuzi** [comment]
For info, the `cache` operator has been removed since RxJS 5.0.0-rc.1.

**Comment by cyrilletuzi** [comment]
It's only used here
https://github.com/angular/mobile-toolkit/blob/5d562fb9b58901aed19a3569d14df19561caf7bd/service-worker/worker/src/companion/comm.ts

but I don't know what's the new solution is

**Comment by rcanu** [comment]
Installing **rxjs** via `npm install -g rxjs` might help

**Comment by gatimus** [comment]
From what I understand you can replace https://github.com/angular/mobile-toolkit/blob/5d562fb9b58901aed19a3569d14df19561caf7bd/service-worker/worker/src/companion/comm.ts#L110 `.cache(1);` with `.publishReplay(1).refCount();` but I don't understand the source well enough to be able to test. 

Also with Rxjs update you'd be able to update https://github.com/angular/mobile-toolkit/blob/5d562fb9b58901aed19a3569d14df19561caf7bd/service-worker/worker/src/companion/comm.ts#L72 and https://github.com/angular/mobile-toolkit/blob/5d562fb9b58901aed19a3569d14df19561caf7bd/service-worker/worker/src/companion/comm.ts#L129 to `Observable.fromPromise()`.
