### ISSUE TITLE
--mobile flag doesnt create manifest.json or app shell

### ISSUE THREAD

**Issue by shubhamkes** [angular/mobile-toolkit#118]
I am using angular-cli: 1.0.0-beta.28.3 .
ng new hello-mobile --mobile   
Trying --mobile but its not creating extra component for mobile

**Comment by gatimus** [comment]
"(Note: this recipe is based on version 1.0.0-beta.4 of Angular CLI.)" -https://mobile.angular.io/guides/

I believe the `--mobile` flag is disabled in `@angular/cli` and `angular-cli`  currently.

**Comment by MatteoNY** [comment]
Opps!  Just exploring at this time.  using latest Angular-CLI  version: 1.0.0-rc.0. I can compile but not really mobile. 

FYI: The documentation appears to be out of date and still using system.js when webpack is now in the latest Angular-CLI  for web. Tutorial using older material2 as import.

Also confused why the need for the app-shell?  from docs: " App Shell is an architecture that focuses on providing an instant-loading experience to users by rendering a "shell" The latest Angular-CLI does auto refresh in the browser. It would be great if the mobile experience could update a connected USB device or allow the dist to be updated so the device can refresh in a hot-load vs stop/start. Alternatively, let NG Serve have an IP address to access. Nice to have. 

Thanks for all the hard work :-)

**Comment by mgechev** [comment]
This issue seems related to https://github.com/angular/mobile-toolkit/issues/124. I believe it can be closed.
