### ISSUE TITLE
When does it available on angular-cli

### ISSUE THREAD

**Issue by johnqiuwan** [angular/mobile-toolkit#124]
I think a lot of people including me is waiting for this "--mobile" feature to integrate to official angular-cli. It makes a lot easier to make PWA 😄

**Comment by mgechev** [comment]
There's an integrated support for Service Workers. Take a look at this e2e test in the [Angular CLI](https://github.com/angular/angular-cli/blob/f3644a939c15f7533e5b240005f7247b8219f646/tests/e2e/tests/build/service-worker.ts) repo.

**Comment by webmaxru** [comment]
The integration with @angular/service-worker is implemented differently in angular-cli: https://github.com/angular/angular-cli/commit/cb2e418
I'm working on PR to the documentation
