### ISSUE TITLE
remove rxjs/add/operator and rxjs/add/observable imports

### ISSUE THREAD

**Issue by IgorMinar** [angular/mobile-toolkit#128]
https://github.com/angular/mobile-toolkit/blob/e399a972e521d769ddafdd50bb03fc3e1bcccf34/service-worker/worker/src/companion/comm.ts#L13-L34

```
import 'rxjs/add/observable/concat';
import 'rxjs/add/observable/defer';
import 'rxjs/add/observable/empty';
import 'rxjs/add/observable/from';
import 'rxjs/add/observable/fromEvent';
import 'rxjs/add/observable/merge';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/timer';
import 'rxjs/add/operator/concatMap';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/expand';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/first';
import 'rxjs/add/operator/let';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/publishReplay';
import 'rxjs/add/operator/reduce';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/take';
import 'rxjs/add/operator/takeWhile';
```

these imports present in companion library pull monkey-patch the operators on the prorotype both at compile time and at runtime. this creates a footgun that can easily break app developers that accidentally start depending on the operators without importing them themselves.

please convert this code to the much uglier version that uses Function#call. See @angular/router for the example usage.

I'm working with @blesh to fix this using something like a `pipe` operator: https://twitter.com/IgorMinar/status/844348523869016066

**Comment by thw0rted** [comment]
Hello from the future! Good news, as of Angular 5 you're using an rxjs that encourages [lettable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md), so this will Just Work when you use the library as intended.

**Comment by whyboris** [comment]
Hello from a further future! _lettable operators_ are now called _pipeable-operators_ https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md :trollface:

**Comment by IgorMinar** [comment]
thanks. This repo is however obsolete now, so we can close this issue. The new development of the angular service-worker is happening here: https://github.com/angular/angular/tree/master/packages/service-worker
