### ISSUE TITLE
Using the NgServiceWorker Provider in Browsers that don't support SW causes error

### ISSUE THREAD

**Issue by treyrich** [angular/mobile-toolkit#132]
Browsers (Safari, Edge) that don't support SW aren't able to run when using the NgServiceWorker provider. Safari throws the error:
`TypeError: undefined is not an object (evaluating 'this.container.controller')`

**Comment by gkalpak** [comment]
We have been bitten by this on angular/angular (here is our workaround angular/angular#15731).

**Comment by treyrich** [comment]
Fixed with eeb4b22bfbd1ddc8c2923b4a4e95ea77f7830fb0
