### ISSUE TITLE
Service Workers: Do not include hidden files

### ISSUE THREAD

**Issue by marcalj** [angular/mobile-toolkit#144]
It's generating an entry for this files I don't want to (and for some files server sent an error):
"/n-angular4/assets/images/.DS_Store": "374c18e42d8f8db505a664b9a4d7c05a72a8e98a",
 "/n-angular4/.htaccess": "acc66ba6ea6b44e39ed00bc41a97c93d0211ae04",

In ```ngsw-manifest.json  static.urls```.

**Comment by webmaxru** [comment]
There is `ignore` section where you can list these files: https://github.com/angular/mobile-toolkit/commit/cafb10c8e074a9f4400fce836f821ea2321f672a#diff-deeb3e9b0e918021db25f13ba4a6ef36

**Comment by marcalj** [comment]
Ok it's working like this:

ngsw-manifest.json
```
{
    "static.ignore": [
        ".htaccess",
        ".DS_Store"
    ]
}
```

You cannot make it work like this:
```
{
    "static": { ignore": [".htaccess", ".DS_Store"] }
}
```

--> ```Error: Manifest already contains key: static```
