### ISSUE TITLE
"routing" not working on deployed Azure

### ISSUE THREAD

**Issue by bob-lee** [angular/mobile-toolkit#146]
Hi, I needs some help on using @angular/service-worker:

my website is static and shows some images, it seems working well on localhost, when reloading the page on offline, the page is served from ServiceWorker ok but after deployed on Azure [here](https://joanne-lee.azurewebsites.net/home), reloading ".../home" page shows "This site can't be reached" message. it works only if specific address is provided like ".../index.html". My ngsw.mainifest.json looks like:
`{
  "routing": {
    "index": "/index.html",
    "routes": {
      "/": {
        "prefix": false
      },
      "/home": {
        "prefix": false
      }
    }
  },
  "external": {
    "urls": [
      {
        "url": "https://fonts.googleapis.com/css?family=Quicksand|Tangerine"
      }
    ]
  }
}`

**Comment by webmaxru** [comment]
Hi!
I see only auto-generated entries in `ngsw-manifest.json`:
https://joanne-lee.azurewebsites.net/ngsw-manifest.json

Are you sure you named/located your custom manifest file properly so it will be merged to the auto-generated one?

Pro tip: you can check NGSW log by opening the URL: https://joanne-lee.azurewebsites.net/ngsw.log

**Comment by bob-lee** [comment]
Hi Maxim, apparently merging is not happening for some reason. Can you please check my source [here](https://github.com/bob-lee/joanne-lee/blob/master/ngsw.manifest.json)? `ng build --prod` doesn't seems to make any change on autogenerated `/dist/ngsw.manifest.json` but when testing on localhost by `node server.js`, custom manifest on `/ngsw.manifest.json` somehow seems to take effect.

**Comment by webmaxru** [comment]
Wrong filename. Should be `ngsw-manifest.json`

**Comment by bob-lee** [comment]
Perfect! Thanks Maxim, looking forward to see documents update soon ;)

**Comment by webmaxru** [comment]
You are welcome! Please share your further experience with NGSW, it's important for the team to get the feedback from real-life usecases :)
