### ISSUE TITLE
Routing options in ngsw-manifest do not work with useHash location strategy

### ISSUE THREAD

**Issue by kiwikern** [angular/mobile-toolkit#154]
In my AppModule I import the RouterModule with hashes as location strategy:
```typescript
RouterModule.forRoot(appRoutes, {useHash: true}),
```

In my ngsw-manifest.json I've tried different routing configurations, e.g.:
```typescript
"routing": {
  "index": "/index.html",
  "routes": {
    "/": {
      "prefix": true
    }
```
With `useHash: true` only the root path is available offline. If I change it to normal routing, all routes are available offline.

**Comment by webmaxru** [comment]
This is because query string part of URL is not ignored at the moment. Try to go for regexp way of the routes definition

**Comment by kiwikern** [comment]
Thanks for your quick reply. Without (knowingly) changing anything, it seems to work now.

**Comment by MrAntix** [comment]
this worked for me

```
    "routes": {
      "/": {
        "prefix": false
      },
      "^/#/.*": {
        "match": "regex"
      }
    }
```
