### ISSUE TITLE
How to use with 3rd party Gulpfiles

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/mobile-toolkit#158]
So my scenario is the following:
- I am using angular cli to build the project
- I have configured Service worker support with `@angular/service-worker`
- I am using [Polymer CLI](https://github.com/Polymer/polymer-cli) to build my google polymer dependencies and have a customized [polymer build](https://github.com/Polymer/polymer-build)

The question that arises for me now is: How can I use the normal "angular way" of building my app (with `ng build --prod` but still build up a build pipe line with Polymer CLI.

I know that you guys offer a Gulp build configuration but I am not sure how it lives together with the normal ng build tools? Do I need to run both `ng build --prod` and then the mobile-toolkit gulpfile and then the polymer build? Or is `ng build --prod` obsolete if I use the mobile-toolkit?

**Comment by mgechev** [comment]
You can find more details regarding the integration with Angular CLI [here](https://github.com/angular/mobile-toolkit/issues/138).

Angular CLI uses webpack, you won't need the gulp plugin provided by the mobile toolkit.

**Comment by BorntraegerMarc** [comment]
@mgechev Thanks for the response. Yes, I am quite aware that Angular CLI uses webpack and that I do not **need** to use the gulp plugin. However: I need to customize my build for the service worker generation.

And the generated sources from the Polymer build are a big part of this service worker generation. So I need to create a build where the two builds can talk to each other. Which is not possible with webpack and gulp.

Do you know how to solve that problem?

**Comment by mgechev** [comment]
You can eject the CLI application and modify the webpack configuration according to your needs. For this purpose you can use the webpack plugin for generation of manifest file.

**Comment by BorntraegerMarc** [comment]
@mgechev agreed. This is what we already are doing. But then the problem arises how we let the modified webpack configuration talk with another gulp task (Polymer build)? I thought it may be easier to use the mobile-toolkit gulpfile to exchange info which files have been processed...

This was my original question. Sorry, I think I formulated it a bit pragmatic :)

**Comment by BorntraegerMarc** [comment]
Sorry, never saw this part: https://github.com/angular/angular-cli/blob/f3644a939c15f7533e5b240005f7247b8219f646/tests/e2e/tests/build/service-worker.ts

This actually solves the problem on how to run 3rd party tasks. Thx!
