### ISSUE TITLE
CLI does not provide --mobile option anymore

### ISSUE THREAD

**Issue by m98** [angular/mobile-toolkit#170]
Since the `--mobile` option is removed (https://github.com/angular/angular-cli/pull/4143), we need to update the documentation on https://mobile.angular.io/guides/cli-setup.html which uses `--mobile` to teach something about the web manifest.

Now when you use `ng new something --mobile`, you will get a warning message which says:

> The option '--mobile' is not registered with the new command. Run `ng new --help` for a list of supported options.

**Comment by kevinSuttle** [comment]
Furthermore, we need a way to generate progressive Angular apps.

**Comment by m98** [comment]
@kevinSuttle Yes, why not.

I don't know if this repository is active or not! No comment from maintinars

**Comment by Splaktar** [comment]
No, unfortunately this repo is not actively maintained and issues and PRs are mostly not being addressed.

**Comment by kevinSuttle** [comment]
@Splaktar That's a shame.

**Comment by mgechev** [comment]
The Angular service worker will be moved to https://github.com/angular/angular (see https://github.com/angular/angular/pull/17276).

At this point the `--mobile` flag is not enabled, however, support in the CLI exists use: ` ng set app.0.serviceWorker=true`.

**Comment by webmaxru** [comment]
@m98 @kevinSuttle you will find all the latest Angular Service Worker info here: https://bit.ly/pwa-angularsummit-2017

**Comment by Sangeethaself** [comment]
is there any updation of --mobile flag added in angular/cli?
