### ISSUE TITLE
Angular cli's service worker resulting in calls happening twice

### ISSUE THREAD

**Issue by Scipionh** [angular/mobile-toolkit#186]
I have just installed Angular cli's service worker by simply setting :
  ```
"apps": [
    { "serviceWorker": true }
  ]
```

I have an api running on my port 9002 and I am calling it in the `ngOnInit `of my `AppComponent`

I now see the call twice, once to my `localhost:9002` and one to my service worker. I tried changing the API and the data are updated correctly in both. I am just not sure why is the call happening twice ? 

**EDIT:**

I just realized it was the same for some static resources as inline.bundle.js, so maybe, it's just me getting confused as I see the calls twice in the network tab ?

![inline](https://user-images.githubusercontent.com/12384987/31112969-504d5e9c-a817-11e7-8b02-04b684be927c.png)

**Comment by webmaxru** [comment]
It's correct. NGSW by default precaches all the files from dist folder (check the resulting ngsw-manifest.json to see the exact list). And yes, SW requests these resources separately from the main thread, so after all browser loads them twice.

**Comment by Scipionh** [comment]
I am a bit confused, isn't the purpose of caching to avoid having to do the call from the main thread ?

**Comment by webmaxru** [comment]
On the first start of PWA you do this double job: you app (index.html) is loading assets (to render the app for the user), and your service worker is loading the same assets (to cache them for the future use)
On the next starts of PWA your app is still requesting the assets (as regular), but now thanks to SW you can serve the responses from the cache (it's up to your SW logic).

**Comment by Scipionh** [comment]
Cheers mate
