### ISSUE TITLE
Option for native potential

### ISSUE THREAD

**Issue by NathanWalker** [angular/mobile-toolkit#23]
@jeffbcross I regret not tracking ya' at ngConf, really wanted to chat a couple options with you and this toolkit, which I love. Great job on the presentation btw.

The gist of what I wanted to run by you is the possibility of a `--native` flag in addition to `--mobile` flag which could generate a NativeScript shell (or even ReactNative, whichever user prefers). I could certainly help provide a PR over next 2 weeks which would essentially do following:

```
$ ng new hello-mobile --mobile --native
$ cd hello-mobile
```

Then run the app:

```
$ ng run ios
```
or...
```
ng run android
```

There's a lot of nice things that could be done here with regards to this but that'd be my first base run.
If multiple native runtimes were supported we could provide something like this:
```
$ ng new hello-mobile --mobile --nativescript
...or...
$ ng new hello-mobile --mobile --reactnative
```

**Comment by NathanWalker** [comment]
The goal would be to always generate a `web` shell (from the `--mobile` flag), so users would get their mobile **web** app to address the major points from your presentation (the web platform advantages with reach, etc), but then also give them the power to create native experiences as an added bonus on top of that since both platforms (web and native) have pros and cons, this would allow them to achieve a synergistic approach to their app development.

**Comment by NathanWalker** [comment]
The integration would look much like what is available right now with `nativescript-ng2-magic`: https://www.npmjs.com/package/nativescript-ng2-magic

It works great with angular-cli today as outlined here: https://github.com/NativeScript/nativescript-angular/issues/225#issuecomment-218069863

Working on a tighter integration would truly make it as simple as possible.

**Comment by jeffbcross** [comment]
@NathanWalker I agree there should be a way to create an app with Web + NativeScript (or other native runtime) with CLI. Right now, the CLI doesn't have a great extensibility story, so any such work has to be done in the CLI repo itself. I think angular/angular-cli#698 is the best place to keep the discussion going.

**Comment by NathanWalker** [comment]
Thank you @jeffbcross 👍
