### ISSUE TITLE
Exception "No provider for Token originUrl!"

### ISSUE THREAD

**Issue by yepzy** [angular/mobile-toolkit#25]
When I want to build my application I've got this exception "No provider for token originurl!". Maybe, I think there is a link with the configuration of the file **src/main-app-shell.ts**, because there is no class APP_BASE_HREF in the **@angular/router**, so I have deleted the line. Is it that, my problem ? How can I resolve it ?
thanks in advance,

**Comment by mgechev** [comment]
App shell is not dependent on `APP_BASE_HREF` neither `originUrl`.

`APP_BASE_HREF` is now in `@angular/common`, so you can reuse it from there. Try to import the token from the proper path and configure the corresponding provider this way. If this doesn't work, would you remove app-shell from your project and see whether you can still reproduce the issue?

**Comment by yepzy** [comment]
I don't understand how to do 
> Try to import the token from the proper path and configure the corresponding provider this way.

but I try with remove the app-shell from my project and it's work

**Comment by mgechev** [comment]
Here's what I mean:

```ts
import {APP_BASE_HREF} from '@angular/common';

bootstrap(AppComponent, [
  provide(APP_BASE_HREF, { useValue: 'your path' }),
  ...
]);
```

**Comment by yepzy** [comment]
It doesn't work, I will try again the guide 
thanks for your help

**Comment by gdi2290** [comment]
this is a problem with universal where you need to specify an Origin Url for Xhr
