### ISSUE TITLE
Can't get routes to render using App Shell

### ISSUE THREAD

**Issue by drejohnson** [angular/mobile-toolkit#34]
I created a repo: https://github.com/drejohnson/angular2-mobile-toolkit with my setup and can't figure out how to get my routes to render.

**Comment by drejohnson** [comment]
Figured out I needed to add `*shellNoRender` anchor tag that uses `[routerLink]`

**Comment by julienboulay** [comment]
@drejohnson : could you push your fix on your repo please, I can not make routes work with mobile shell too.
Thanks

**Comment by drejohnson** [comment]
@julienboulay updated

**Comment by julienboulay** [comment]
@drejohnson Many thanks !

**Comment by julienboulay** [comment]
@drejohnson : I've found why my sample app was not working : it seems that when no [routerLink] directive exists in the page, the route cannot be navigated when typing its url in the browser.
To reproduce it : 

- remove the toolbar component from app.component.ts
- try to add '/home' in the url

The route /home is not displayed.

**Comment by julienboulay** [comment]
As a workaround, I've just added `style="display:none;"` to the link, because I may use DOM event (onClick) and component functions to drive the navigation, for the moment :
`<a style="display:none;" [routerLink]="['/start']" *shellNoRender><span>Start</span></a>`
