### ISSUE TITLE
design(AppShell): case sensitivity of the App Shell Runtime Parser marker

### ISSUE THREAD

**Issue by mgechev** [angular/mobile-toolkit#60]
Using case sensitive attribute names as markers in the generated by the Universal template will not work with the app shell runtime parser. Currently the runtime parser uses parse5 which serializes the HTML AST without keeping the case sensitivity.

Options to proceed:

- Short term solution is using class name as a marker.
- For longer term solution consider:
   - Using the Angular template parser for producing the AST.
   - Forking parse5 and introducing case sensitivity, ES2015 modules (allow easier tree-shaking), and payload reduction.

**Comment by mgechev** [comment]
Today I did some experiments with the Angular's `TemplateParser`. Everything seems to work well, even without existing in the schema attributes.

We do not have serialized for the produced AST so we can reuse the serializer from Parse5, which is not destructive in sense of case sensitivity. In order to pass the produced by the `TemplateParser` AST to the Parse5 serializer we'd have to adapt it.

**Comment by jeffbcross** [comment]
> We'll be able to tree-shake everything (even parse5 with this plugin), and maintain as less code as possible.

Do you have an idea how small the minified output would be (and how it compares to just using parse5, without case-sensitivity)?

Overall sounds good. I'm wondering what cases might break Angular's TemplateParser. Doesn't it blacklist certain tags, like `<script>`?

**Comment by mgechev** [comment]
Based on the latest in-depth research I did, the best option right now is to slightly modify parse5's lexer runtime. This way we will enable case-sensitive parsing. I opened a PR with the case sensitive run-time parser here https://github.com/angular/mobile-toolkit/pull/68. [Here](https://gist.github.com/mgechev/2eeec41262a8c07b37e6fa9a0a927b37) are some brief notes that I did.

**Comment by mgechev** [comment]
Fixed by https://github.com/angular/mobile-toolkit/commit/fb9673aa9feccd655183d1850edfd4ae2b0b48e6
