### ISSUE TITLE
Strange path when I do ng new <name app> --mobile

### ISSUE THREAD

**Issue by ardiadrianadri** [angular/mobile-toolkit#93]
Each time I create a new mobile project with Angular 2 mobile toolkit I get the same error:
ENOENT: no such file or directory, chmod '/vagrant/mobile-test/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv'

Called my attention to the angular-cli seems to want to access a directory node_modules it is on the same path where the cli is running. Then I have had the idea to try to create an new project from my $HOME... and it works well.

Other information:

My development environment is a vagrant virtual machine with an image of Ubuntu 14.04. My version of nodejs and npm are 6.4.0 and 3.10.3 respectively.

---

UPDATE:
I just check that the problem is not with the mobile toolkit, is with vagrant. The npm installation fails if the folder where I'm doing it is synchronized with the host machine. Seems that you can not has a vagrant environment with angular-cli...

**Comment by mgechev** [comment]
The integration with the CLI is now works differently here's the PR by @alxhub. I believe we can close this issue https://github.com/angular/angular-cli/commit/cb2e418.
