### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by hacknaked** [angular/mobile-toolkit#95]
It seems that all work related to mobile support is going to be coded in Angular CLI project. Is there any plan for this project?

**Comment by mgechev** [comment]
The `--mobile` flag of the angular-cli adds integration with the mobile-toolkit. We're working on extensibility of the service-worker support, improvements on the application shell, etc.

Expect updates in the next a couple of weeks.

**Comment by hacknaked** [comment]
@mgechev  Great to hear that, thanks!
